# Generated by Django 5.0.7 on 2024-07-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0002_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='_from',
            new_name='from_user',
        ),
    ]
