# Generated by Django 5.0.7 on 2024-08-01 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0006_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
        migrations.AddField(
            model_name='posts',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='reacted_users', to='Quotes.comments'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='reactors',
            field=models.ManyToManyField(blank=True, related_name='reacted_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
